
<?php
echo  $this->flashCurrent();
?>
<div class="row">
    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">

        <div class="card card-login">
            <div class="card-header text-center" data-background-color="rose">

            </div>
            <div class="card-content">

                <p class="login-box-msg"><?= $this->translate('Register a new membership'); ?></p>

                <?php echo $this->renderForm($form) ?>

                <a href="<?= $this->url('home'); ?>"
                   class="text-center"><?= $this->translate('I already have a membership'); ?></a>
            </div>

        </div>

    </div>

</div>